#+TITLE: Schedule for the UEFA Euro 2020
#+TAGS: EURO2020
#+CATEGORY: EURO2020

* Info
** Schedule from [[https://en.wikipedia.org/wiki/UEFA_Euro_2020]]
** Inspiration and code from [[https://github.com/djcb/org-euro2012/][djcb's EURO2012]] and [[https://github.com/ruediger/org-world-cup2014][ruediger's 2014 World cup]] schedules.
** All times are [[https://en.wikipedia.org/wiki/Central_European_Summer_Time][CEST]] ([[https://en.wikipedia.org/wiki/UTC%252B02:00][UTC+2]]), as listed by UEFA.

Use the following function to change the timezone.  Set =n= to 1 hour for
[[https://fi.wikipedia.org/wiki/UTC%252B3][UTC+3]].  Move to code block and use =C-c C-c= to eval it.

#+HEADERS: :var n=1
#+begin_src emacs-lisp :results silent
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward "[[<]" nil t)
      (when (org-at-timestamp-p t)
        (org-timestamp-change n 'hour))))
#+end_src

* Schedule for the UEFA EURO 2020
** Group A                                                           :GroupA:
*** Turkey - Italy 0-3
<2021-06-11 Fri 21:00>
Stadio Olimpico, Rome

53' 0-1 Merih Demiral (OG)
66' 0-2 Ciro Immobile
79' 0-3 Lorenzo Insigne

*** Wales - Switzerland 1-1
<2021-06-12 Sat 15:00>
Olympic Stadium, Baku

49' 0-1 Breel Embolo
74' 1-1 Kieffer Moore

*** Turkey - Wales 0-2
<2021-06-16 Sat 18:00>
Olympic Stadium, Baku

42' 0-1 Aaron Ramsey
90+5' 0-2 Connor Roberts

*** Italy - Switzerland 3-0
<2021-06-16 Wed 21:00>
Stadio Olimpico, Rome

26' 1-0 Manuel Locatelli
52' 2-0 Manuel Locatelli
89' 3-0 Ciro Immobile

*** Switzerland - Turkey 3-1
<2021-06-20 Sun 18:00>
Olympic Stadium, Baku

6' 1-0 Haris Seferovic
26' 2-0 Xherdan Shaqiri
62' 2-1 Irfan Kahveci
68' 3-1 Xherdan Shaqiri

*** Italy - Wales 1-0
<2021-06-20 Sun 18:00>
Stadio Olimpico, Rome

39' 1-0 Matteo Pessina

** Group B                                                           :GroupB:
*** Denmark - Finland 0-1
<2021-06-12 Sat 18:00>
Parken Stadium, Copenhagen

59' 0-1 Joel Pohjanpalo

*** Belgium - Russia 3-0
<2021-06-12 Sat 21:00>
Krestovsky Stadium, Saint Petersburg

10' 1-0 Romelu Lukaku
34' 2-0 Thomas Meunier
88' 3-0 Romelu Lukaku

*** Finland - Russia 0-1
<2021-06-16 Wed 15:00>
Krestovsky Stadium, Saint Petersburg

45+2' 0-1 Aleksey Miranchuk

*** Denmark - Belgium 1-2
<2021-06-17 Thu 18:00>
Parken Stadium, Copenhagen

2' 1-0 Yussuf Poulsen
54' 1-1 Thorgan Hazard
70' 1-2 Kevin De Bruyne

*** Russia - Denmark 1-4
<2021-06-21 Mon 21:00>
Parken Stadium, Copenhagen

38' 0-1 Mikkel Damsgaard
59' 0-2 Yussuf Poulsen
70' 1-2 Artjom Dzjuba (Penalty)
79' 1-3 Andreas Christensen
82' 1-4 Joakim Mæhle

*** Finland - Belgium 0-2
<2021-06-21 Mon 21:00>
Krestovsky Stadium, Saint Petersburg

74' 0-1 Lukas Hradecký (OG)
81' 0-2 Romelu Lukaku

** Group C                                                           :GroupC:
*** Austria - North Macedonia 3-1
<2021-06-13 Sun 18:00>
Arena Națională, Bucharest

18' 1-0 Stefan Lainer
28' 1-1 Goran Pandev
78' 2-1 Michael Gregoritsch
89' 3-1 Marko Arnautović

*** Netherlands - Ukraine 3-2
<2021-06-13 Sun 21:00>
Johan Cruyff Arena, Amsterdam

52' 1-0 Georginio Wijnaldum
58' 2-0 Wout Weghorst
75' 2-1 Andri Jarmolenko
79' 2-2 Roman Jaremtšuk
85' 3-2 Denzel Dumfries

*** Ukraine - North Macedonia 2-1
<2021-06-17 Thu 15:00>
Arena Națională, Bucharest

29' 1-0 Andri Jarmolenko
34' 2-0 Roman Jaremtšuk
57' 2-1 Ezgjan Alioski

*** Netherlands - Austria 2-0
<2021-06-17 Thu 21:00>
Johan Cruyff Arena, Amsterdam

11' 1-0 Memphis Debay (Penalty)
67' 2-0 Denzel Dumfries

*** North Macedonia - Netherlands 0-3
<2021-06-21 Mon 18:00>
Johan Cruyff Arena, Amsterdam

24' 0-1 Memphis Depay
51' 0-2 Georginio Wijnaldum
58' 0-3 Georginio Wijnaldum

*** Ukraine - Austria 0-1
<2021-06-21 Mon 18:00>
Arena Națională, Bucharest

21' 0-1 Christoph Baumgartner

** Group D                                                           :GroupD:
*** England - Croatia 1-0
<2021-06-13 Sun 15:00>
Wembley Stadium, London

1-0 57' Raheem Sterling

*** Scotland - Czech Republic 0-2
<2021-06-14 Mon 15:00>
Hampden Park, Glasgow

42' 0-1 Patrik Schick
52' 0-2 Patrik Schick

*** Croatia - Czech Republic 1-1
<2021-06-18 Fri 18:00>
Hampden Park, Glasgow

37' 0-1 Patrik Schick (Penalty)
47' 1-1 Ivan Perišić

*** England - Scotland 0-0
<2021-06-18 Fri 21:00>
Wembley Stadium, London
*** Croatia - Scotland 3-1
<2021-06-22 Tue 21:00>
Hampden Park, Glasgow

17' 1-0 Nikola Vlašić
42' 1-1 Callum McGregor
62' 2-1 Luka Modrić
76' 3-1 Ivan Perišić

*** Czech Republic - England 0-1
<2021-06-22 Tue 21:00>
Wembley Stadium, London

12' 0-1 Raheem Sterling

** Group E                                                           :GroupE:
*** Poland - Slovakia 1-2
<2021-06-14 Mon 18:00>
Krestovsky Stadium, Saint Petersburg

18' 0-1 Wojciech Szczęsny (OG)
46' 1-1 Karol Linetty
62' Grzegorz Krychowiak (Red card)
69' 1-2 Milan Škriniar

*** Spain - Sweden 0-0
<2021-06-14 Mon 21:00>
La Cartuja, Seville
*** Sweden - Slovakia 1-0
<2021-06-18 Fri 15:00>
Krestovsky Stadium, Saint Petersburg

77' 1-0 Emil Forsberg (Penalty)

*** Spain - Poland 1-1
<2021-06-19 Sat 21:00>
La Cartuja, Seville

25' 1-0 Álvaro Morata
54' 1-1 Robert Lewandowski

*** Slovakia - Spain 0-5
<2021-06-23 Wed 18:00>
La Cartuja, Seville

30' 0-1 Martin Dúbravka (OG)
45+3' 0-2 Aymeric Laporte
56' 0-3 Pablo Sarabia
67' 0-4 Ferran Torres
71' 0-5 Juraj Kucka (OG)

*** Sweden - Poland 3-2
<2021-06-23 Wed 18:00>
Krestovsky Stadium, Saint Petersburg

2' 1-0 Emil Forsberg
59' 2-0 Emil Forsberg
61' 2-1 Robert Lewandowski
84' 2-2 Robert Lewandowski
90+3' 3-2 Viktor Claesson

** Group F                                                           :GroupF:
*** Hungary - Portugal 0-3
<2021-06-15 Tue 18:00>
Puskás Aréna, Budapest

84' 0-1 Raphaël Guerreiro
87' 0-2 Cristiano Ronaldo (Penalty)
90+2' 0-3 Cristiano Ronaldo

*** France - Germany 1-0
<2021-06-15 Tue 21:00>
Allianz Arena, Munich

20' 1-0 Mats Hummels (OG)

*** Hungary - France 1-1
<2021-06-19 Sat 15:00>
Puskás Aréna, Budapest

45+2' 1-0 Attila Fiola
66' 1-1 Antoine Griezmann

*** Portugal - Germany 2-4
<2021-06-19 Sat 18:00>
Allianz Arena, Munich

15' 1-0 Cristiano Ronaldo
35' 1-1 Rúben Dias (OG)
39' 1-2 Raphaël Guerreiro (OG)
51' 1-3 Kai Havertz
60' 1-4 Robin Gosens
67' 2-4 Diogo Jota

*** Portugal - France 2-2
<2021-06-23 Wed 21:00>
Puskás Aréna, Budapest

30' 1-0 Cristiano Ronaldo (Penalty)
45+2' 1-1 Karim Benzema (Penalty)
47' 1-2 Karim Benzema
60' 2-2 Cristiano Ronaldo (Penalty)

*** Germany - Hungary 2-2
<2021-06-23 Wed 21:00>
Allianz Arena, Munich

11' 0-1 Ádám Szalai
66' 1-1 Kai Havertz
68' 1-2 András Schäfer
84' 2-2 Leon Goretzka

** Round of 16                                                    :RoundOf16:
*** Italy - Austria 2-1                                             :Match37:
<2021-06-26 Sat 21:00>
Wembley Stadium, London

95' 1-0 Federico Chiesa
105' 2-0 Matteo Pessina
114' 2-1 Saša Kalajdžić

*** Wales - Denmark 0-4                                             :Match38:
<2021-06-26 Sat 18:00>
Johan Cruyff Arena, Amsterdam

27' 0-1 Kasper Dolberg
48' 0-2 Kasper Dolberg
88' 0-3 Joakim Mæhle
90+4' 0-4 Martin Braithwaite

*** Belgium - Portugal 1-0                                          :Match39:
<2021-06-27 Sun 21:00>
La Cartuja, Seville

42' 1-0 Thorgan Hazard

*** Netherlands - Czech Republic 0-2                                :Match40:
<2021-06-27 Sun 18:00>
Puskás Aréna, Budapest

55' Matthijs de Ligt (Red card)
68' 0-1 Tomáš Holeš
80' 0-2 Patrik Schick

*** France - Switzerland 3-3 (4-5)                                  :Match41:
<2021-06-28 Mon 21:00>
Arena Națională, Bucharest

15' 0-1 Haris Seferović
57' 1-1 Karim Benzema
59' 2-1 Karim Benzema
75' 3-1 Paul Pogba
81' 3-2 Haris Seferović
90' 3-3 Mario Gavranović

Penalty shoot-out:

0-1 Mario Gavranović
1-1 Paul Pogba
1-2 Fabian Schär
2-2 Olivier Giroud
2-3 Manuel Akanji
3-3 Marcus Thuram
3-4 Rubén Vargas
4-4 Presnel Kimpembe
4-5 Admir Mehmedi
4-5 Kylian Mbappé

*** Croatia - Spain 3-5                                             :Match42:
<2021-06-28 Mon 18:00>
Parken Stadium, Copenhagen

20' 1-0 Pedri (OG)
38' 1-1 Pablo Sarabia
57' 1-2 César Azpilicueta
76' 1-3 Ferran Torres
85' 2-3 Mislav Oršić
90+2' 3-3 Mario Pašalić
100' 3-4 Álvaro Morata
103' 3-5 Mikel Oyarzabal

*** Sweden - Ukraine 1-2                                            :Match43:
<2021-06-29 Tue 21:00>
Hampden Park, Glasgow

27' 0-1 Oleksandr Zintšenko
43' 1-1 Emil Forsberg
99' Marcus Danielson (Red card)
120+1' 1-2 Artem Dovbyk

*** England - Germany 2-0                                           :Match44:
<2021-06-29 Tue 18:00>
Wembley Stadium, London

75' 1-0 Raheem Sterling
86' 2-0 Harry Kane

** Quarter finals                                                  :QtFinals:
*** Switzerland - Spain 1-1 (1-3)                                   :Match45:
<2021-07-02 Fri 18:00>
Krestovsky Stadium, Saint Petersburg

8' 0-1 Denis Zakaria (OG)
68' 1-1 Xherdan Shaqiri
77' Remo Freuler (Red card)

0-0 Sergio Busquets
1-0 Mario Gavranović
1-1 Dani Olmo
1-1 Fabian Schär
1-1 Rodrigo Hernández
1-1 Manuel Akanji
1-2 Gerard Moreno
1-2 Rubén Vargas
1-3 Mikel Oyarzabal

*** Belgium - Italy 1-2                                             :Match46:
<2021-07-02 Fri 21:00>
Allianz Arena, Munich

31' 0-1 Nicolò Barella
44' 0-2 Lorenzo Insigne
45+2' 1-2 Romelu Lukaku (Penalty)

*** Czech Republic - Denmark 1-2                                    :Match47:
<2021-07-03 Sat 18:00>
Olympic Stadium, Baku

5' 0-1 Thomas Delaney
42' 0-2 Kasper Dolberg
49' 1-2 Patrik Schick

*** Ukraine - England 0-4                                           :Match48:
<2021-07-03 Sat 21:00>
Stadio Olimpico, Rome

4' 0-1 Harry Kane
46' 0-2 Harry Maguire
50' 0-3 Harry Kane
63' 0-4 Jordan Henderson

** Semi-finals                                                   :SemiFinals:
*** Italy - Spain 1-1 (4-2)                                         :Match49:
<2021-07-06 Tue 21:00>
Wembley Stadium, London

60' 1-0 Federico Chiesa
80' 1-1 Álvaro Morata

0-0 Manuel Locatelli
0-0 Dani Olmo
1-0 Andrea Belotti
1-1 Gerard Moreno
2-1 Leonardo Bonucci
2-2 Thiago Alcântara
3-2 Federico Bernardeschi
3-2 Álvaro Morata
4-2 Jorginho

*** England - Denmark 2-1                                           :Match50:
<2021-07-07 Wed 21:00>
Wembley Stadium, London

30' 0-1 Mikkel Damsgaard
39' 1-1 Simon Kjær
104' 2-1 Harry Kane

** Final                                                              :Final:
*** Italy - England 1-1 (3-2)
<2021-07-11 Sun 21:00>
Wembley Stadium, London

2' 0-1 Luke Shaw
67' 1-1 Leonardo Bonucci

1-0 Domenico Berardi
1-1 Harry Kane
1-1 Andrea Belotti
1-2 Harry Maguire
2-2 Leonardo Bonucci
2-2 Marcus Rashford
3-2 Federico Bernardeschi
3-2 Jadon Sancho
3-2 Jorginho
3-2 Bukayo Saka
